name: ci
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install project + dev extras
        run: pip install -e ".[dev]"

      - name: Type check (mypy)
        run: mypy .

      - name: Lint (pylint)
        run: pylint lipm_walking_controller || true  # drop `|| true` if you want hard fail